### ISSUE TITLE
Having trouble with local variables 

### ISSUE THREAD

**Issue by asdase26** [asdase26/LEGO-Battles-companion#1]
Heres the error
===========================================
================ RESTART: /home/jerichosettlersfarm/guess.py ================
Welcome to the LEGO Battles Companion
Programmed by Asa Fasching
This program will keep track of unit health, armour and battle points. Press enter to continue
Please enter the name of player 1 >>>Asa
Please enter the name of player 2 >>>Gus
Now that we have established players let's head to the main menu
||MAIN MENU|| 
Name of player 1: Asa
Name of player 2: Gus
1:Start Game 
2:Set a timer 
3:Edit unit stats 
4:Quit 
1
Alright! Get ready to play!
Would you like to use a timer if you have set one? y/nn
Ok, no timer
Roll a d8 do decide who goes first, when you are done press enter
Who going first? Asa or Gus? >>>Asa
Asa is going first!
Asa is going first
Press enter when Asas turn is done
Did Asa hold any checkpoints this turn?yes
Press enter when Asas turn is done
Did Asa hold any checkpoints this turn?y
How many?1
Traceback (most recent call last):
  File "/home/jerichosettlersfarm/guess.py", line 84, in <module>
    mainMenu()
  File "/home/jerichosettlersfarm/guess.py", line 59, in mainMenu
    startGame("n")
  File "/home/jerichosettlersfarm/guess.py", line 26, in startGame
    pointCount(currentPlayer)  #passing currentPlayer to pointCount
  File "/home/jerichosettlersfarm/guess.py", line 39, in pointCount
    p2bp = p2bp + (numberCheckpoints * 20)
UnboundLocalError: local variable 'p2bp' referenced before assignment
>>>

**Comment by asdase26** [comment]
Fixed it!
